apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
  labels:
    app: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app : user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
        - name: user-management
          image: thuji98/user-management:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9012

---

apiVersion: v1
kind: Service
metadata:
  name:  user-management
spec:
  selector:
    app:  user-management
  ports:
    - nodePort: 30170
      port: 9012
      targetPort: 9012
      protocol: TCP
  type: NodePort